### ISSUE TITLE
New option: Download all images with status 'AVAILABLE_FOR_DOWNLOAD'

### ISSUE THREAD

**Issue by willmacs** [eodms-sgdot/eodms-cli#16]
##### DEPENDANCIES

Requires mechanism in EODMS to return orders by status

##### DRIVER

Often users have outstanding downloads that have been fulfilled, but not downloaded. This option would allow users to simply download every outstanding that is ready.

**Comment by keballantyne** [comment]
This feature has been added in v3.0.0 as Process 4.
