### ISSUE TITLE
sar-toolbox support

### ISSUE THREAD

**Issue by willmacs** [eodms-sgdot/eodms-cli#30]
Context

eodms-sgdot/eodms_factory#28

**Comment by neilbrub** [comment]
Hey there, thanks for the great work on eodms-cli! It's been an awesome tool to facilitate access to EODMS data.

I'm wondering if anyone might be able to comment on the existence or status of plans for SAR toolbox support through eodms-cli for vetted user accounts? This would be a great addition to the processing workflow for accessing analysis-ready SAR imagery.

Cheers,
Neil

**Comment by willmacs** [comment]
Hi @neilbrub, this ticket is the driver for exactly this, sar toolbox support in eodms-cli. Right now, SAR Toolbox orders can only be submitted in the UI. However, there already exists a mechanism to pass SAR Toolbox JSON through the existing `order/` endpoint, we just need to wrap those JSON blobs as proper SAR toolbox processing categories e.g. Radiometry, Ortho-rectification and mosaic, Filters, Utilities, Polarimetry, and Interferometry. Thanks for your interest, we will update this ticket with progress as it happens.

**Comment by neilbrub** [comment]
Thanks for the quick reply @willmacs! I'll keep my eyes on this ticket. Any ideas on the coarse (e.g. quarterly) timeline for this feature?

**Comment by willmacs** [comment]
[INSAR_Processing.json](https://github.com/eodms-sgdot/eodms-cli/files/15296962/INSAR_Processing.json)
[SAR_Processing_R2.json](https://github.com/eodms-sgdot/eodms-cli/files/15296963/SAR_Processing_R2.json)
[SAR_Processing_RCM.json](https://github.com/eodms-sgdot/eodms-cli/files/15296961/SAR_Processing_RCM.json)

**Comment by keballantyne** [comment]
SAR Toolbox ordering and downloading has been added to eodms-cli with release of [v3.6.0](https://github.com/eodms-sgdot/eodms-cli/releases/tag/v3.6.0).
