### ISSUE TITLE
misc fixes related to maxResults, pagination NAPL open_data search not hardcoded

### ISSUE THREAD

**Issue by willmacs** [eodms-sgdot/eodms-cli#47]
- `maxResults` should default to 1500
- Remove pagination, do not use `firstResult`
- Fix search fields which are not working e.g. `NAPL.PREVIEW_AVAILABLE`, do not hardcode `open_data` = true.

**Comment by keballantyne** [comment]
Issues have been divided between eodms-cli and py-eodms-rapi:

- `maxResults` should default to 1500 (issue #49 )
- Remove pagination, do not use `firstResult` (issue eodms-sgdot/py-eodms-rapi#40)
- Fix search fields which are not working e.g. `NAPL.PREVIEW_AVAILABLE`
- Do not hardcode `open_data` = true (issue #48 )
